[package]
authors = ["David Hewitt <david.hewitt.92@gmail.com>"]
name = "password-check"
version = "0.2.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
reqwest = "0.11"
rpassword = "5.0"
sha1 = "0.6"
tokio = { version = "1.0", features = ["macros", "rt"] }
